export const FILTER = 'FILTER';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const DELETE_FAVORITE_CATEGORIES = 'DELETE_FAVORITE_CATEGORIES';

export const NO_ACTION = 'NO_ACTION';
export const SET_COUNTRIES = 'SET_COUNTRIES';
export const SET_EVENTS = 'SET_EVENTS';
export const SET_FAVORITES = 'SET_FAVORITES';
export const SET_FAVORITES_CATEGORIES = 'SET_FAVORITES_CATEGORIES';
export const SET_PERSONAL = 'SET_PERSONAL';
export const SET_OWN = 'SET_OWN';
export const SET_MINE = 'SET_MINE';
export const SET_BLOCK = 'SET_BLOCK';
export const ADD_BLOCK = 'ADD_BLOCK';
export const REMOVE_BLOCK = 'REMOVE_BLOCK';
export const SET_BLOCKED = 'SET_BLOCKED';
export const SET_LOGIN_TYPE = 'SET_LOGIN_TYPE';

export const SET_CHAT = 'SET_CHAT';
export const CREATE_CHAT = 'CREATE_CHAT';
export const UPDATE_CHAT = 'UPDATE_CHAT';
export const ORDER_CHATS = 'ORDER_CHATS';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_USER = 'SET_USER';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_LANGUAGES = 'SET_LANGUAGES';
export const SET_USER_INSPECTED = 'SET_USER_INSPECTED';
export const LOG_OUT = 'LOG_OUT';

export const ADD_FAVORITE_CATEGORY = 'ADD_FAVORITE_CATEGORY';
export const REMOVE_FAVORITE_CATEGORY = 'REMOVE_FAVORITE_CATEGORY';
